FROM ubuntu:latest

RUN apt update && apt install -y software-properties-common
RUN apt update && apt install -y --allow-unauthenticated \
    clang \
    clang-tidy \
    clang-format \
    clangd \
    make \
    ninja-build \
    cmake
