name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc manpages-posix manpages-posix-dev

      - name: Проверка наличия Makefile
        run: |
          if [ ! -f Makefile ]; then
            echo "Makefile not found!"
            exit 1
          fi

      - name: Сборка проекта
        run: |
          make clean
          make CFLAGS="-Wall -Wextra -std=c11 -fsanitize=address -g -fPIC -D_POSIX_C_SOURCE=200809L"

      - name: Запуск тестов
        run: |
          export LD_LIBRARY_PATH=.
          ./build/main > output.txt
          cat output.txt

      - name: Проверка вывода теста
        run: |
          if grep -q "Read from cache: Hello, cache!" output.txt; then
            echo "Test passed!"
            exit 0
          else
            echo "Test failed!"
            exit 1
          fi

      - name: Проверка утечек памяти с AddressSanitizer
        run: |
          export LD_PRELOAD=$(gcc -print-file-name=libasan.so)
          ./build/main > asan_output.txt
          if grep -qi "ERROR" asan_output.txt; then
            echo "Memory leaks detected!"
            exit 1
          fi
          echo "No memory leaks found."

      - name: Очистка после тестов
        run: make clean
